#!/usr/bin/env bash
# gen-env-examples.sh — keep a committed .env.example next to every stack, listing
# the environment variables that stack's compose file references, with values
# BLANK (or the compose-provided default). Also writes docs/env-inventory.md,
# a repo-wide key x stack table.
#
#   tools/gen-env-examples.sh            # write / update the files
#   tools/gen-env-examples.sh --check    # CI: regenerate to a temp, fail on drift
#
# SAFETY: values come ONLY from `${VAR:-default}` in compose. Real .env files are
# read for KEY NAMES ONLY (to catch keys injected via `env_file:` that never
# appear as ${VAR}); their values are never read, printed, or written.
#
# A stack dir may also have a git-tracked `.env.example.extra` (KEY[=default]
# per line) for vars a helper script reads directly from that stack's .env —
# never as ${VAR} in the compose file, so this generator can't discover them
# any other way. See monitoring/.env.example.extra for the pattern.
set -uo pipefail
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || { cd "$(dirname "$0")/.." && pwd; })"
cd "$ROOT"

MODE="write"; [ "${1:-}" = "--check" ] && MODE="check"
INV="docs/env-inventory.md"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
INV_ROWS="$TMP/inv.tsv"; : > "$INV_ROWS"
drift=0

list_repo_files() {
  local g; g="$(git ls-files 2>/dev/null || true)"
  if [ -n "$g" ]; then printf '%s\n' "$g"
  else find . -type f -not -path './.git/*' | sed 's|^\./||'
  fi
}

env_file_targets() {   # $1 = compose file
  awk '
    /^[[:space:]]*env_file:[[:space:]]*\[/ { s=$0; sub(/.*\[/,"",s); sub(/\].*/,"",s);
      n=split(s,a,","); for(i=1;i<=n;i++){ gsub(/[[:space:]"'\'']/,"",a[i]); if(a[i]!="") print a[i] } next }
    /^[[:space:]]*env_file:[[:space:]]*[^[:space:]#]/ { v=$2; gsub(/["'\'']/,"",v); print v; next }
    /^[[:space:]]*env_file:[[:space:]]*$/ { blk=1; next }
    blk && /^[[:space:]]*-[[:space:]]*/ { v=$2; gsub(/["'\'']/,"",v); print v; next }
    blk { blk=0 }
  ' "$1"
}

mapfile -t COMPOSE < <(list_repo_files | grep -E '(^|/)(docker-)?compose\.ya?ml$' | sort -u)
[ "${#COMPOSE[@]}" -gt 0 ] || { echo "no compose files found"; exit 1; }

emit_example() {   # $1 = compose file path
  local f="$1" d stack out live k name def tok
  d="$(dirname "$f")"; stack="$(basename "$d")"; [ "$d" = "." ] && stack="root"

  local -A KV=()
  # ${VAR} / ${VAR:-default} / ${VAR:?} / ${VAR-default}
  while IFS= read -r tok; do
    name="${tok#\$\{}"; name="${name%\}}"
    case "$name" in
      *:-*)  def="${name#*:-}";  name="${name%%:-*}"  ;;
      *:\?*) def="";             name="${name%%:\?*}" ;;
      *:+*)  def="";             name="${name%%:+*}"  ;;
      *-*)   def="${name#*-}";   name="${name%%-*}"   ;;
      *)     def=""                                   ;;
    esac
    [[ "$name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
    if [ -z "${KV[$name]+set}" ]; then KV[$name]="$def"
    elif [ -z "${KV[$name]}" ] && [ -n "$def" ]; then KV[$name]="$def"
    fi
  done < <(grep -oE '\$\{[A-Za-z_][A-Za-z0-9_]*(:?[-?+][^}]*)?\}' "$f" || true)

  # names injected via env_file: (names only)
  while IFS= read -r ef; do
    [ -n "$ef" ] || continue
    [ -f "$d/$ef" ] || continue
    while IFS= read -r k; do
      [ -z "${KV[$k]+set}" ] && KV[$k]=""
    done < <(sed -nE 's/^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)=.*/\1/p' "$d/$ef")
  done < <(env_file_targets "$f")

  # hand-maintained extras: vars consumed by something other than this
  # compose file's ${VAR} interpolation (e.g. a helper script that reads the
  # stack's .env directly) — not derivable from the compose file, so they
  # can't come from the two blocks above. Committed, git-tracked, one
  # KEY[=default] per line; '#'-comments and blank lines ignored.
  if [ -f "$d/.env.example.extra" ]; then
    while IFS= read -r k; do
      [ -z "$k" ] && continue
      case "$k" in \#*) continue ;; esac
      name="${k%%=*}"; def=""
      [[ "$k" == *=* ]] && def="${k#*=}"
      [[ "$name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
      if [ -z "${KV[$name]+set}" ]; then KV[$name]="$def"
      elif [ -z "${KV[$name]}" ] && [ -n "$def" ]; then KV[$name]="$def"
      fi
    done < "$d/.env.example.extra"
  fi

  [ "${#KV[@]}" -eq 0 ] && return 0

  out="$TMP/$d/.env.example"; mkdir -p "$(dirname "$out")"
  {
    echo "# $stack — env vars referenced by $(basename "$f")."
    echo "# Generated by tools/gen-env-examples.sh — do not hand-edit; re-run it."
    echo "# Real values go in $d/.env (gitignored). Names + compose defaults only here."
    echo
    while IFS= read -r k; do
      printf '%s=%s\n' "$k" "${KV[$k]}"
      printf '%s\t%s\t%s\n' "$stack" "$k" "${KV[$k]}" >> "$INV_ROWS"
    done < <(printf '%s\n' "${!KV[@]}" | LC_ALL=C sort)
  } > "$out"

  live="$d/.env.example"
  if [ "$MODE" = check ]; then
    if ! diff -q "$live" "$out" >/dev/null 2>&1; then
      echo "DRIFT: $live"; diff -u "$live" "$out" 2>/dev/null | sed 's/^/    /'; drift=1
    fi
  else
    if ! diff -q "$live" "$out" >/dev/null 2>&1; then cp "$out" "$live"; echo "updated $live (${#KV[@]} keys)"
    else echo "ok      $live"; fi
  fi
}

for f in "${COMPOSE[@]}"; do emit_example "$f"; done

INVOUT="$TMP/env-inventory.md"
{
  echo "# Environment variable inventory"
  echo
  echo "_Generated by \`tools/gen-env-examples.sh\` — one row per (stack, key)._"
  echo "_For anything sensitive, record where the real value lives in \`docs/secrets.md\`._"
  echo
  echo "| stack | key | compose default |"
  echo "|---|---|---|"
  LC_ALL=C sort -u "$INV_ROWS" | while IFS=$'\t' read -r s k v; do
    printf '| %s | `%s` | %s |\n' "$s" "$k" "${v:-—}"
  done
} > "$INVOUT"

if [ "$MODE" = check ]; then
  diff -q "$INV" "$INVOUT" >/dev/null 2>&1 || { echo "DRIFT: $INV"; drift=1; }
  if [ $drift -eq 0 ]; then echo "all .env.example files + $INV in sync."
  else echo; echo "fix: run  tools/gen-env-examples.sh  and commit the result."; exit 1; fi
else
  mkdir -p "$(dirname "$INV")"
  if ! diff -q "$INV" "$INVOUT" >/dev/null 2>&1; then cp "$INVOUT" "$INV"; echo "updated $INV"
  else echo "ok      $INV"; fi
fi
